<a href="https://colab.research.google.com/github/J-o-y-y/codeslave/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
matrix_1 = [[1, 2],[3, 4]]
matrix_2 = [[5, 6],[7, 8]]


In [ ]:
matrix_result= []
for i in range(len(matrix_1)):
    tmp = []
    for j in range(len(matrix_2)):
        tmp.append(matrix_1[i][j]+matrix_2[i][j])
    matrix_result.append(tmp)

print(matrix_result)


[[6, 8], [10, 12]]


In [ ]:
import numpy as np

matrix_result = np.array(matrix_1) + np.array(matrix_2)
print(matrix_result)


[[ 6  8]
 [10 12]]


In [ ]:
matrix_1 = [[1, 2],[3, 4]]

In [ ]:
matrix_1 = [[1, 2],[3, 4]]

for i in range(len(matrix_1)):
    for j in range(len(matrix_2)):
        matrix_1[i][j] = matrix_1[i][j] + 1

print(matrix_1)


[[2, 3], [4, 5]]


In [ ]:
matrix_1 = np.array(matrix_1) + 1

In [ ]:
matrix_1 = [[1, 2],[3, 4]]

In [ ]:
np.array(matrix_1)+1

array([[2, 3],
       [4, 5]])

In [ ]:
x = np.uint(32)
print(x.dtype) #uint64

uint64


In [ ]:
x = np.array([1, 2, 3, 4])
print(x.dtype) #int64

int64


In [ ]:
x = np.float32([1, 2, 3, 4])
print(x.dtype) #float32

float32


In [ ]:
x

array([1., 2., 3., 4.], dtype=float32)

In [ ]:
x = np.array([1, 2, 3, 4], dtype=np.float32)
print(x.dtype) #

float32


In [ ]:
x = np.int32(x)
print(x.dtype)
np.issubdtype(x.dtype, np.int32) #float32


int32


True

In [ ]:
x = np.array(1)
print(x.shape) # ()
print(x.ndim) # 0
print(x.size) # 1


()
0
1


In [ ]:
x = np.array([1, 2])
print(x.shape) # (2, )
print(x.ndim) # 1
print(x.size) # 2


(2,)
1
2


In [ ]:
x = np.array([[1, 2, 3],[4, 5, 6]])
print(x.shape) # (2, 3)
print(x.ndim) # 2
print(x.size) # 6


(2, 3)
2
6


In [ ]:
x = np.arange(10)
print(x)


[0 1 2 3 4 5 6 7 8 9]


In [ ]:
x = np.arange(10.0)
print(x)


[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


In [ ]:
x = np.arange(1, 10, 2)
print(x)


[1 3 5 7 9]


In [ ]:
x = np.arange(1, 10, 0.5)
print(x)


[1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5 9.  9.5]


In [ ]:
x = np.arange(10, 1, -0.5)
print(x)


[10.   9.5  9.   8.5  8.   7.5  7.   6.5  6.   5.5  5.   4.5  4.   3.5
  3.   2.5  2.   1.5]


In [ ]:
x = np.linspace(1, 20, 5)
print(x)


[ 1.    5.75 10.5  15.25 20.  ]


In [ ]:
x = np.linspace(1, 20, 10, endpoint=False)
print(x)


[ 1.   2.9  4.8  6.7  8.6 10.5 12.4 14.3 16.2 18.1]


In [ ]:
x = np.arange(9).reshape(3, 3)
print(x) # 2차원


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
x = np.arange(24).reshape(2, 3, 4)
print(x) # 3차원


[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
x = np.arange(16).reshape(2, 2, 2, 2)
print(x) # 4차원


[[[[ 0  1]
   [ 2  3]]

  [[ 4  5]
   [ 6  7]]]


 [[[ 8  9]
   [10 11]]

  [[12 13]
   [14 15]]]]


In [ ]:
x = np.array([[1,2],[3,4],[5,6]])
print(x)


[[1 2]
 [3 4]
 [5 6]]


In [ ]:
print(x.reshape(2,3)) # 데이터를 유지하고 형태변경

[[1 2 3]
 [4 5 6]]


In [ ]:
x = np.arange(9).reshape(3, -1)
print(x) #개수에 맞춰 생성


[[0 1 2]
 [3 4 5]
 [6 7 8]]


In [ ]:
# 1차원 슬라이싱
x = np.arange(20)
x


array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [ ]:
x[:10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [ ]:
# 2차원 슬라이싱
x = np.arange(20).reshape(4,5)
print(x)
print(x[1:3])
print(x[1:3, 1:3])


[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]
[[ 5  6  7  8  9]
 [10 11 12 13 14]]
[[ 6  7]
 [11 12]]


In [ ]:
a = np.arange(20).reshape(4, 5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
print(a[1][1])


6


In [ ]:
print(a[1,1])

6


In [ ]:
print(a[[1,1],[1,2]])

[6 7]


In [ ]:
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
# boolean indexing
print(a > 3)


[[False False False False  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]
 [ True  True  True  True  True]]


In [ ]:
print(a[a > 3])


[ 4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
print(a[a == 1])

[1]


In [ ]:
print(a[~(a == 1)])

[ 0  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
print(a[(a > 3)&(a < 8)])

[4 5 6 7]


In [ ]:
np.random.rand(5,5)

array([[0.75574647, 0.94532163, 0.77960466, 0.65704878, 0.26320043],
       [0.35111878, 0.95783857, 0.78964156, 0.74824546, 0.41072141],
       [0.21863332, 0.37579872, 0.14725671, 0.62559326, 0.05231925],
       [0.62866096, 0.29931563, 0.91139953, 0.56743009, 0.66708275],
       [0.36087951, 0.91656026, 0.63051484, 0.28393481, 0.29688829]])

In [ ]:
np.random.randint(1, 10)

4

In [ ]:
np.random.randint(1, 10, size=(5,5))

array([[6, 2, 1, 3, 9],
       [7, 5, 1, 3, 6],
       [4, 9, 4, 4, 3],
       [7, 6, 9, 6, 3],
       [2, 3, 4, 4, 7]])

In [ ]:
np.random.choice(100, size=(3, 4))
x = np.array([1, 2, 3, 4, 5, 6, 7, 8])
np.random.choice(x, size=(2, 2))

array([[66, 50, 53,  4],
       [ 7, 89, 68, 61],
       [42, 23,  2, 26]])

In [ ]:
np.ones([5, 5])

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
np.zeros([5, 5])

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [ ]:
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [ ]:
x = np.arange(1, 4)
y = np.arange(4, 7)

x


array([1, 2, 3])

In [ ]:
y

array([4, 5, 6])

In [ ]:
np.concatenate([x, y])

array([1, 2, 3, 4, 5, 6])

In [ ]:
x = np.arange(10).reshape(2, 5)
y = np.arange(10, 20).reshape(2, 5)



In [ ]:
x

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

In [ ]:
y

array([[10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:

np.concatenate([x, y])

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [ ]:
np.concatenate([x, y], axis=1)

array([[ 0,  1,  2,  3,  4, 10, 11, 12, 13, 14],
       [ 5,  6,  7,  8,  9, 15, 16, 17, 18, 19]])

In [ ]:
x = np.arange(12)
np.split(x, 4)


[array([0, 1, 2]), array([3, 4, 5]), array([6, 7, 8]), array([ 9, 10, 11])]

In [ ]:
x = np.arange(16).reshape(4, 4)
x


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [ ]:
np.split(x, 2)


[array([[0, 1, 2, 3],
        [4, 5, 6, 7]]),
 array([[ 8,  9, 10, 11],
        [12, 13, 14, 15]])]

In [ ]:
x = np.arange(16).reshape(4, 4)
np.split(x, 2, axis=1)


[array([[ 0,  1],
        [ 4,  5],
        [ 8,  9],
        [12, 13]]),
 array([[ 2,  3],
        [ 6,  7],
        [10, 11],
        [14, 15]])]

In [ ]:
x = np.array([1,2,3])
x + 1


array([2, 3, 4])

In [ ]:
x = np.arange(1, 10).reshape(3, 3)
y = np.arange(1, 4)
x + y


array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [ ]:
x = np.array([10, 20, 30]).reshape(3, 1)
y = np.arange(1, 4)
x + y


array([[11, 12, 13],
       [21, 22, 23],
       [31, 32, 33]])

In [ ]:
x = np.arange(4).reshape(2, 2)
y = np.arange(4).reshape(2, 2)

np.mean(x) # 평균

1.5

In [ ]:

np.median(x) # 중앙값

1.5

In [ ]:

np.std(x) # 표준편차

1.118033988749895

In [ ]:

np.var(x) # 분산

1.25

In [ ]:

np.sum(x) # 합

6

In [ ]:
np.where(x > 3)

(array([], dtype=int64), array([], dtype=int64))

In [ ]:
x

array([[0, 1],
       [2, 3]])

In [ ]:
x = [1, 2, 3, 4, 5, 6, 7, 8, 9]
y = [10, 20, 30, 40, 50, 60, 70, 80, 90]

In [ ]:
import numpy as np

x = np.array(x).reshape(3,3)
y = np.array(y).reshape(3,3)

In [ ]:
x + y

array([[11, 22, 33],
       [44, 55, 66],
       [77, 88, 99]])

In [ ]:
x.dot(y)

array([[ 300,  360,  420],
       [ 660,  810,  960],
       [1020, 1260, 1500]])

In [ ]:
np.linspace(1,20,30) + 10


array([11.        , 11.65517241, 12.31034483, 12.96551724, 13.62068966,
       14.27586207, 14.93103448, 15.5862069 , 16.24137931, 16.89655172,
       17.55172414, 18.20689655, 18.86206897, 19.51724138, 20.17241379,
       20.82758621, 21.48275862, 22.13793103, 22.79310345, 23.44827586,
       24.10344828, 24.75862069, 25.4137931 , 26.06896552, 26.72413793,
       27.37931034, 28.03448276, 28.68965517, 29.34482759, 30.        ])

In [ ]:
x = np.arange(4).reshape(2, 2)
x

array([[0, 1],
       [2, 3]])

In [ ]:
np.where(x > 2, x, -100) # 조건, True 일경우, False 일경우

array([[-100, -100],
       [-100,    3]])

In [ ]:
#1~100까지 난수가 들어가있는 2x10x10 배열을 만들고
#50보다 크거나 같은값은 1, 50보다 작은값은 2로 변환하고
#2번째 배열에 아래와 같이 붉은색 위치만 뽑아주세요

x = np.random.randint(1, 100, size=(2,10, 10))
x2 = np.where(x >= 50, 1, 2)

print(x)
print(x2)

[[[45 10 86 51 95 69 77 67 69 45]
  [28 14 95 36 38 80 25 52 42 29]
  [ 7 92 63 98 21 12 20 36 36 25]
  [72  6 39 55 82 49 94 13 26 29]
  [49 68 22 48 46 55 43 37 96 20]
  [86 38 40 27 70 68 32 17  1 55]
  [66 15 62 30  1 41 46 21 90 95]
  [10 73 11 87 90 88 99 53 59 56]
  [90 66 65 35 69 75 98 95 90 68]
  [82  6 56 19  5  7 58 13  7 44]]

 [[37 69 19 63 30 30 51 53 31 29]
  [30  2 63 55  7 26 81 93 84 11]
  [31 47 82 26 40 12 93 80 76 19]
  [14 90 77 79 22 99 31 60 80 78]
  [15 82 49 33 28 25 13  3 13 32]
  [47 48 60 33 12 99 23 61 56 76]
  [96 32 49 12 43 23 35 67 51 27]
  [35  2 72  7 66 99 48 13 94  5]
  [92 32 34 32 26 27 29  6 27 53]
  [51 44 66 80 94 25 61 29 13 97]]]
[[[2 2 1 1 1 1 1 1 1 2]
  [2 2 1 2 2 1 2 1 2 2]
  [2 1 1 1 2 2 2 2 2 2]
  [1 2 2 1 1 2 1 2 2 2]
  [2 1 2 2 2 1 2 2 1 2]
  [1 2 2 2 1 1 2 2 2 1]
  [1 2 1 2 2 2 2 2 1 1]
  [2 1 2 1 1 1 1 1 1 1]
  [1 1 1 2 1 1 1 1 1 1]
  [1 2 1 2 2 2 1 2 2 2]]

 [[2 1 2 1 2 2 1 1 2 2]
  [2 2 1 1 2 2 1 1 1 2]
  [2 2 1 2 2 2 1 1 1 2]
  

In [ ]:
x2[1][5:,5:]

array([[1, 2, 1, 1, 1],
       [2, 2, 1, 1, 2],
       [1, 2, 2, 1, 2],
       [2, 2, 2, 2, 1],
       [2, 1, 2, 2, 1]])

In [ ]:
import pandas as pd
import numpy as np

x = [1, 2, 3, 4, 5]
X = pd.Series(x) # Series 생성
X

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
X[2]

3

In [ ]:
# 넘파이 리스트도 사용가능
x = np.array([1, 2, 3, 4, 5])
pd.Series(x)


0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:
x = [1, 2, 3, 4, 5]
x = pd.Series(x)
x

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [ ]:

x[0] # 1



1

In [ ]:
x[1: 3] # 2, 3


1    2
2    3
dtype: int64

In [ ]:
x[::-1] # 5, 4, 3, 2, 1


4    5
3    4
2    3
1    2
0    1
dtype: int64

In [ ]:
x[x > 3]


3    4
4    5
dtype: int64

In [ ]:
x + 1 # 2, 3, 4, 5, 6

0    2
1    3
2    4
3    5
4    6
dtype: int64

In [ ]:
x * 10 # 10, 20, 30, 40, 50



0    10
1    20
2    30
3    40
4    50
dtype: int64

In [ ]:
x + x # 2, 4, 6, 8, 10

0     2
1     4
2     6
3     8
4    10
dtype: int64

In [ ]:
x = [1, 2, 3, 4, 5]
x = pd.Series(x)

print(x.index) # 인덱스
print(x.values) # 값


RangeIndex(start=0, stop=5, step=1)
[1 2 3 4 5]


In [ ]:

x = [1, 2, 3, 4, 5]
x = pd.Series(x, index=['a','b','c','d','e'])

x

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [ ]:
x['a']

1

In [ ]:
print(x['a']) # 명시적 인덱스접근
print(x[0]) # 묵시적 인덱스접근

1
1


In [ ]:
print(x[['a','e']]) # 팬시색인, 한번에 여러값 접근


a    1
e    5
dtype: int64


In [ ]:
print(x.a) # 또다른 접근방법

1


In [ ]:
x = {"수학":90, "영어":80, "과학":95, "미술":80}
x = pd.Series(x)
x


수학    90
영어    80
과학    95
미술    80
dtype: int64

In [ ]:
x['수학']

90

In [ ]:
# 슬라이싱 가능
x['영어':]


영어    80
과학    95
미술    80
dtype: int64

In [ ]:
x['영어':'미술']

영어    80
과학    95
미술    80
dtype: int64

In [ ]:
student_1 = {"수학":90, "영어":80, "과학":95, "미술":80}
student_2 = {"수학":70, "영어":90, "과학":100, "미술":70}

#index_1 = ['홍길동','홍길동','홍길동','홍길동','이몽룡','이몽룡','이몽룡','이몽룡']
index_1 = ['홍길동' for i in range(len(student_1))] + ['이몽룡' for i in range(len(student_2))]

#index_2 = ['수학','영어','과학','미술','수학','영어','과학','미술']
index_2 = [i for i in student_1] + [i for i in student_2]

value_all = list(student_1.values()) + list(student_2.values())

students = pd.Series(value_all, index=[index_1, index_2])
students

홍길동  수학     90
     영어     80
     과학     95
     미술     80
이몽룡  수학     70
     영어     90
     과학    100
     미술     70
dtype: int64

In [ ]:
x = [1, None, 2, None, 3, 4, None]
x = pd.Series(x)


In [ ]:
print(x.sum()) # 10
print(x.max()) # 4
print(x.min()) # 1


10.0
4.0
1.0


In [ ]:
print(x.isnull().sum()) # 3
print(x.notnull().sum()) # 4


3
4


In [ ]:
#결측값 제거
x.dropna()

#결측값을 다른값으로 채우기
x.fillna(0)


0    1.0
1    0.0
2    2.0
3    0.0
4    3.0
5    4.0
6    0.0
dtype: float64

In [ ]:
x = pd.Series([1, 2, 3])
y = pd.Series([4, 5, 6])
z = pd.Series([7, 8, 9])

print(x)
print(y)
print(z)

X = pd.concat([x, y, z])

0    1
1    2
2    3
dtype: int64
0    4
1    5
2    6
dtype: int64
0    7
1    8
2    9
dtype: int64


In [ ]:
X[0]

0    1
0    4
0    7
dtype: int64

In [ ]:
pd.concat([x, y, z], verify_integrity=True)

ValueError: ignored

In [ ]:
# 합치면서 인덱스 번호를 다시정리
pd.concat([x, y, z], ignore_index=True)

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [ ]:
# 축변경
pd.concat([x, y, z], ignore_index=True, axis=1)

0  1  2
0  1  4  7
1  2  5  8
2  3  6  9

In [ ]:
x = pd.Series([1, 2, 3, 4])
y = pd.Series([4, 5, 6])
z = pd.Series([7, 8, 9])

# 개수가 맞지 않을경우 교집합
pd.concat([x, y, z], ignore_index=True, axis=1, join='inner')


0  1  2
0  1  4  7
1  2  5  8
2  3  6  9

In [ ]:

# 개수가 맞지 않을경우 합집합
pd.concat([x, y, z], ignore_index=True, axis=1, join='outer')

0    1    2
0  1  4.0  7.0
1  2  5.0  8.0
2  3  6.0  9.0
3  4  NaN  NaN

In [ ]:
x = pd.Series([1, 2, 3, 4, 5])
y = pd.Series([6, 7, 8, 9, 0])


In [ ]:

# 더하기
print(x.add(10))
print(x.add(y))

# 빼기
print(x.sub(y))

# 곱하기
print(x.mul(y))



0    11
1    12
2    13
3    14
4    15
dtype: int64
0     7
1     9
2    11
3    13
4     5
dtype: int64
0   -5
1   -5
2   -5
3   -5
4    5
dtype: int64
0     6
1    14
2    24
3    36
4     0
dtype: int64


In [ ]:
pd.date_range(start='2019-01-01', end='2019-01-07')

DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-05', '2019-01-06', '2019-01-07'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
pd.date_range(start='2019-01-01', periods=7)

DatetimeIndex(['2019-01-01', '2019-01-02', '2019-01-03', '2019-01-04',
               '2019-01-05', '2019-01-06', '2019-01-07'],
              dtype='datetime64[ns]', freq='D')

In [ ]:
pd.date_range(start='2019-01-01', periods=7, freq='2D')

DatetimeIndex(['2019-01-01', '2019-01-03', '2019-01-05', '2019-01-07',
               '2019-01-09', '2019-01-11', '2019-01-13'],
              dtype='datetime64[ns]', freq='2D')

In [ ]:
pd.date_range(start='2019-01-01', periods=7, freq='W')

DatetimeIndex(['2019-01-06', '2019-01-13', '2019-01-20', '2019-01-27',
               '2019-02-03', '2019-02-10', '2019-02-17'],
              dtype='datetime64[ns]', freq='W-SUN')

In [ ]:
x = pd.to_datetime(['2020-01-02 03:45', '2021-12-24 23:59'])
x.year



Int64Index([2020, 2021], dtype='int64')

In [ ]:
x.weekday


Int64Index([3, 4], dtype='int64')

In [ ]:
diff = x - pd.to_datetime('2020-02-12 15:39')

In [ ]:
diff

TimedeltaIndex(['-42 days +12:06:00', '681 days 08:20:00'], dtype='timedelta64[ns]', freq=None)

In [ ]:
#아래 코드를 실행하고 Series Y 에서

#결측값의 개수를 구하고
#결측값을 제거한 Series 를 만들고
#결측값에 y의 평균값을 넣은 Series 를 만들어주세요.

x = [np.nan, 1, 2, 3, 4, 5]
y = pd.Series([x[np.random.randint(0, 6)] for i in range(20)])

y

0     3.0
1     3.0
2     4.0
3     3.0
4     1.0
5     2.0
6     3.0
7     2.0
8     4.0
9     NaN
10    NaN
11    NaN
12    3.0
13    2.0
14    2.0
15    4.0
16    3.0
17    4.0
18    4.0
19    1.0
dtype: float64

In [ ]:
y.isnull().sum()

3

In [ ]:
y.dropna()

0     3.0
1     3.0
2     4.0
3     3.0
4     1.0
5     2.0
6     3.0
7     2.0
8     4.0
12    3.0
13    2.0
14    2.0
15    4.0
16    3.0
17    4.0
18    4.0
19    1.0
dtype: float64

In [ ]:
y.fillna(y.mean())

0     3.000000
1     3.000000
2     4.000000
3     3.000000
4     1.000000
5     2.000000
6     3.000000
7     2.000000
8     4.000000
9     2.823529
10    2.823529
11    2.823529
12    3.000000
13    2.000000
14    2.000000
15    4.000000
16    3.000000
17    4.000000
18    4.000000
19    1.000000
dtype: float64

In [ ]:
sales_data = {
    '연도':[2015, 2016, 2017, 2018, 2019, 2020],
    '판매량':[103, 70, 130, 160, 190, 230],
    '매출':[500000, 300000, 400000, 550000, 700000, 680000],
    '순이익':[370000, 190000, 300000, 480000, 600000, 590000]
}

df = pd.DataFrame(sales_data)

In [ ]:
df

연도  판매량      매출     순이익
0  2015  103  500000  370000
1  2016   70  300000  190000
2  2017  130  400000  300000
3  2018  160  550000  480000
4  2019  190  700000  600000
5  2020  230  680000  590000

In [ ]:
a = pd.Series([103, 500000, 370000], ['판매량', '매출', '순이익'])
b = pd.Series([70, 300000, 190000], ['판매량', '매출', '순이익'])
c = pd.Series([130, 400000, 190000], ['판매량', '매출', '순이익'])

df = pd.DataFrame([a, b, c], index=[2015, 2016, 2017])
df

판매량      매출     순이익
2015  103  500000  370000
2016   70  300000  190000
2017  130  400000  190000

In [ ]:
df['판매량']

2015    103
2016     70
2017    130
Name: 판매량, dtype: int64

In [ ]:
df.판매량

2015    103
2016     70
2017    130
Name: 판매량, dtype: int64

In [ ]:
df[['판매량', '매출']]

판매량      매출
2015  103  500000
2016   70  300000
2017  130  400000

In [ ]:
df[2:3]

판매량      매출     순이익
2017  130  400000  190000

In [ ]:
df.iloc[1]

판매량        70
매출     300000
순이익    190000
Name: 2016, dtype: int64

In [ ]:
df.iloc[[1, 2]]

판매량      매출     순이익
2016   70  300000  190000
2017  130  400000  190000

In [ ]:
df.loc[2015]

판매량       103
매출     500000
순이익    370000
Name: 2015, dtype: int64

In [ ]:
df.loc[[2015, 2017], ['판매량', '매출']]

판매량      매출
2015  103  500000
2017  130  400000

In [ ]:
sales_data = {
    '연도':[2015, 2016, 2017, 2018, 2019, 2020],
    '판매량':[103, 70, 130, 160, 190, 230],
    '매출':[500000, 300000, 400000, 550000, 700000, 680000],
    '순이익':[370000, 190000, 300000, 480000, 600000, 590000]
}


In [ ]:
pd.DataFrame(sales_data, columns=['판매량','매출','순이익'], index=sales_data['연도'])

판매량      매출     순이익
2015  103  500000  370000
2016   70  300000  190000
2017  130  400000  300000
2018  160  550000  480000
2019  190  700000  600000
2020  230  680000  590000

In [ ]:
sales_data = pd.read_csv('sales_data.csv', index_col='연도', header=0, sep=',')

In [ ]:
sales_data

판매량      매출     순이익
연도                       
2015  103  500000  370000
2016   70  300000  190000
2017  130  400000  300000
2018   60  550000  480000
2019  190  700000  600000
2020  230  680000  590000

In [ ]:
sales_data.to_csv('sales_data_save.csv', encoding='utf-8')

In [ ]:
sales_data = {
    '연도':[2015, 2016, 2017, 2018, 2019, 2020],
    '판매량':[103, 70, 130, 160, 190, 230],
    '매출':[500000, 300000, 400000, 550000, 700000, 680000],
    '순이익':[370000, 190000, 300000, 480000, 600000, 590000]
}
sales_data = pd.DataFrame(sales_data)

In [ ]:
sales_data

연도  판매량      매출     순이익
0  2015  103  500000  370000
1  2016   70  300000  190000
2  2017  130  400000  300000
3  2018  160  550000  480000
4  2019  190  700000  600000
5  2020  230  680000  590000

In [ ]:
sales_data['순이익율'] = (sales_data['순이익']/sales_data['매출']) * 100

In [ ]:
sales_data

연도  판매량      매출     순이익       순이익율
0  2015  103  500000  370000  74.000000
1  2016   70  300000  190000  63.333333
2  2017  130  400000  300000  75.000000
3  2018  160  550000  480000  87.272727
4  2019  190  700000  600000  85.714286
5  2020  230  680000  590000  86.764706

In [ ]:
def check(n):
    if n > 80:
        return '높음'
    else:
        return '낮음'


In [ ]:
sales_data['순이익율_비교'] = sales_data['순이익율'].apply(check)
sales_data


연도  판매량      매출     순이익       순이익율 순이익율_비교
0  2015  103  500000  370000  74.000000      낮음
1  2016   70  300000  190000  63.333333      낮음
2  2017  130  400000  300000  75.000000      낮음
3  2018  160  550000  480000  87.272727      높음
4  2019  190  700000  600000  85.714286      높음
5  2020  230  680000  590000  86.764706      높음

In [ ]:
# 인덱스에 조건가능
sales_data[sales_data['매출'] > 300000]


연도  판매량      매출     순이익       순이익율 순이익율_비교
0  2015  103  500000  370000  74.000000      낮음
2  2017  130  400000  300000  75.000000      낮음
3  2018  160  550000  480000  87.272727      높음
4  2019  190  700000  600000  85.714286      높음
5  2020  230  680000  590000  86.764706      높음

In [ ]:
sales_data['테스트1'] = np.where(sales_data['판매량'] > 200, 0, sales_data['판매량'])

In [ ]:
sales_data

연도  판매량      매출     순이익       순이익율 순이익율_비교  테스트1
0  2015  103  500000  370000  74.000000      낮음   103
1  2016   70  300000  190000  63.333333      낮음    70
2  2017  130  400000  300000  75.000000      낮음   130
3  2018  160  550000  480000  87.272727      높음   160
4  2019  190  700000  600000  85.714286      높음   190
5  2020  230  680000  590000  86.764706      높음     0

In [ ]:
# 해당 조건에 일치하는것만 바꾸고 나머지는 NaN
sales_data['테스트2'] = sales_data[sales_data['판매량'] < 100]['판매량'] + 50
sales_data

연도  판매량      매출     순이익       순이익율 순이익율_비교  테스트1   테스트2
0  2015  103  500000  370000  74.000000      낮음   103    NaN
1  2016   70  300000  190000  63.333333      낮음    70  120.0
2  2017  130  400000  300000  75.000000      낮음   130    NaN
3  2018  160  550000  480000  87.272727      높음   160    NaN
4  2019  190  700000  600000  85.714286      높음   190    NaN
5  2020  230  680000  590000  86.764706      높음     0    NaN

In [ ]:
# 행추가
sales_data.loc[6] = [2021, 720000,650000, 360, 0, '',0,0]
sales_data

연도     판매량      매출     순이익       순이익율 순이익율_비교  테스트1   테스트2
0  2015     103  500000  370000  74.000000      낮음   103    NaN
1  2016      70  300000  190000  63.333333      낮음    70  120.0
2  2017     130  400000  300000  75.000000      낮음   130    NaN
3  2018     160  550000  480000  87.272727      높음   160    NaN
4  2019     190  700000  600000  85.714286      높음   190    NaN
5  2020     230  680000  590000  86.764706      높음     0    NaN
6  2021  720000  650000     360   0.000000             0    0.0

In [ ]:
sales_data

연도  판매량      매출     순이익
0  2015  103  500000  370000
1  2016   70  300000  190000
2  2017  130  400000  300000
3  2018  160  550000  480000
4  2019  190  700000  600000
5  2020  230  680000  590000

In [ ]:
sales_data.loc[6] = sales_data.loc[5] + 100

In [ ]:
sales_data

연도  판매량      매출     순이익
0  2015  103  500000  370000
1  2016   70  300000  190000
2  2017  130  400000  300000
3  2018  160  550000  480000
4  2019  190  700000  600000
5  2020  230  680000  590000
6  2120  330  680100  590100

In [ ]:
sales_data1 = {
    '연도':[2015, 2016, 2017, 2018],
    '판매량':[103, 70, 130, 160],
    '매출':[500000, 300000, 400000, 550000],
    '순이익':[370000, 190000, 300000, 480000]
 }


In [ ]:
sales_data2 = {
    '연도':[2019, 2020],
    '판매량':[190, 230],
    '매출':[700000, 680000],
    '순이익':[ 600000, 590000]
}


In [ ]:
sales_df1 = pd.DataFrame(sales_data1)
sales_df2 = pd.DataFrame(sales_data2)


In [ ]:
# append
sales_df1.append(sales_df2, ignore_index=True)


<ipython-input-234-82cd47f273a1>:2: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  sales_df1.append(sales_df2, ignore_index=True)


연도  판매량      매출     순이익
0  2015  103  500000  370000
1  2016   70  300000  190000
2  2017  130  400000  300000
3  2018  160  550000  480000
4  2019  190  700000  600000
5  2020  230  680000  590000

In [ ]:
# concat
pd.concat([sales_df1, sales_df2], ignore_index=True)


연도  판매량      매출     순이익
0  2015  103  500000  370000
1  2016   70  300000  190000
2  2017  130  400000  300000
3  2018  160  550000  480000
4  2019  190  700000  600000
5  2020  230  680000  590000

In [ ]:
sales_data = {
    '연도':[2015, 2016, 2017, 2018, 2019, 2020],
    '판매량':[103, 70, 130, 160, 190, 230],
    '매출':[500000, 300000, 400000, 550000, 700000, 680000],
    '순이익':[370000, 190000, 300000, 480000, 600000, 590000]
}
sales_data = pd.DataFrame(sales_data)

In [ ]:
cost_data = {
    '연도':[2015, 2016, 2017, 2021],
    '이자':[1520, 1120, 1360, 1680],
    '관리비':[650, 400, 750, 800],
    '세금':[12000, 8900, 10900, 12800] }

cost_data = pd.DataFrame(cost_data)

In [ ]:
# merge
pd.merge(sales_data, cost_data, on='연도', how='outer')

연도    판매량        매출       순이익      이자    관리비       세금
0  2015  103.0  500000.0  370000.0  1520.0  650.0  12000.0
1  2016   70.0  300000.0  190000.0  1120.0  400.0   8900.0
2  2017  130.0  400000.0  300000.0  1360.0  750.0  10900.0
3  2018  160.0  550000.0  480000.0     NaN    NaN      NaN
4  2019  190.0  700000.0  600000.0     NaN    NaN      NaN
5  2020  230.0  680000.0  590000.0     NaN    NaN      NaN
6  2021    NaN       NaN       NaN  1680.0  800.0  12800.0

In [ ]:
pd.merge(sales_data, cost_data, on='연도', how='left')

연도  판매량      매출     순이익      이자    관리비       세금
0  2015  103  500000  370000  1520.0  650.0  12000.0
1  2016   70  300000  190000  1120.0  400.0   8900.0
2  2017  130  400000  300000  1360.0  750.0  10900.0
3  2018  160  550000  480000     NaN    NaN      NaN
4  2019  190  700000  600000     NaN    NaN      NaN
5  2020  230  680000  590000     NaN    NaN      NaN

In [ ]:
sales_data['테스트1'] = 'test1'
sales_data['테스트2'] = 'test2'
sales_data['테스트3'] = 'test3'
sales_data

연도  판매량      매출     순이익   테스트1   테스트2   테스트3
0  2015  103  500000  370000  test1  test2  test3
1  2016   70  300000  190000  test1  test2  test3
2  2017  130  400000  300000  test1  test2  test3
3  2018  160  550000  480000  test1  test2  test3
4  2019  190  700000  600000  test1  test2  test3
5  2020  230  680000  590000  test1  test2  test3

In [ ]:
del sales_data['테스트1']
sales_data


연도  판매량      매출     순이익   테스트2   테스트3
0  2015  103  500000  370000  test2  test3
1  2016   70  300000  190000  test2  test3
2  2017  130  400000  300000  test2  test3
3  2018  160  550000  480000  test2  test3
4  2019  190  700000  600000  test2  test3
5  2020  230  680000  590000  test2  test3

In [ ]:
# drop 함수사용, inplace 를 True 로 하여 원본에 적용
sales_data.drop(['테스트2'], axis='columns', inplace=True)


In [ ]:
sales_data

연도  판매량      매출     순이익   테스트1   테스트3
0  2015  103  500000  370000  test1  test3
1  2016   70  300000  190000  test1  test3
2  2017  130  400000  300000  test1  test3
3  2018  160  550000  480000  test1  test3
4  2019  190  700000  600000  test1  test3
5  2020  230  680000  590000  test1  test3

In [ ]:
sales_data.drop(sales_data.columns[[0, 2]], axis='columns', inplace=True)

In [ ]:
sales_data

판매량     순이익   테스트1   테스트3
0  103  370000  test1  test3
1   70  190000  test1  test3
2  130  300000  test1  test3
3  160  480000  test1  test3
4  190  600000  test1  test3
5  230  590000  test1  test3

In [ ]:
sales_data.drop(0, inplace=True)

In [ ]:
sales_data

판매량     순이익   테스트1   테스트3
1   70  190000  test1  test3
2  130  300000  test1  test3
3  160  480000  test1  test3
4  190  600000  test1  test3
5  230  590000  test1  test3

In [ ]:
sales_data.drop([3, 4, 5], inplace=True)
sales_data

판매량     순이익   테스트1   테스트3
1   70  190000  test1  test3
2  130  300000  test1  test3

In [ ]:
df = pd.DataFrame(np.random.randint(1, 100, size=(4, 4)), index=[['A','A','B','B'],['a','b','a','b']],
        columns=[['가가','가가','나나','나나'],['가','나','가','나']])


In [ ]:
df

가가      나나    
      가   나   가   나
A a  51  32  39  57
  b  27  90  85  11
B a  63  97  78  59
  b  37  32  28  22

In [ ]:
df['나나']

가   나
A a  39  57
  b  85  11
B a  78  59
  b  28  22

In [ ]:
df.loc['A']

가가      나나    
    가   나   가   나
a  51  32  39  57
b  27  90  85  11

In [ ]:
# 인덱스확인
df.index


MultiIndex([('A', 'a'),
            ('A', 'b'),
            ('B', 'a'),
            ('B', 'b')],
           )

In [ ]:
# 칼럼확인
df.columns


MultiIndex([('가가', '가'),
            ('가가', '나'),
            ('나나', '가'),
            ('나나', '나')],
           )

In [ ]:
df = pd.DataFrame(np.random.randint(1, 100, size=(8, 2)),
			index=[['A창고','A창고','A창고','A창고','B창고','B창고','B창고','B창고'],
 ['사과','배','바나나','사과','사과','배','바나나','배']],
columns=['판매','재고'])
df.index.names = ['창고명','상품명']
df

판매  재고
창고명 상품명        
A창고 사과   88  33
    배    34  48
    바나나  24  24
    사과   19  47
B창고 사과   79  20
    배    87  45
    바나나   1  72
    배    93  45

In [ ]:
df.groupby('창고명').sum()

판매   재고
창고명          
A창고  165  152
B창고  260  182

In [ ]:
df.groupby('상품명').sum()

판매   재고
상품명          
바나나   25   96
배    214  138
사과   186  100

In [ ]:
df.groupby(['창고명','상품명']).sum()

판매  재고
창고명 상품명         
A창고 바나나   24  24
    배     34  48
    사과   107  80
B창고 바나나    1  72
    배    180  90
    사과    79  20

In [ ]:
df = pd.DataFrame(np.random.randint(1, 100, size=(8, 2)),
			index=[['A창고','A창고','A창고','A창고','B창고','B창고','B창고','B창고'],
 ['사과','배','바나나','사과','사과','배','바나나','배']],
columns=['판매','재고'])

df

판매  재고
A창고 사과   73  74
    배    37  70
    바나나  52  48
    사과   22  29
B창고 사과   33  98
    배    22  30
    바나나  59  53
    배    93  25

In [ ]:
df.sort_values(by="판매", ascending=False)

판매  재고
B창고 배    93  25
A창고 사과   73  74
B창고 바나나  59  53
A창고 바나나  52  48
    배    37  70
B창고 사과   33  98
A창고 사과   22  29
B창고 배    22  30

In [ ]:
#1)아래와 같은 데이터프레임을 만들어주세요. (점수는 1~100까지 랜덤값)
#2) 반별 합계와 평균을 추가해주세요
#3)인덱스 명을 추가하고 학년별 합계를 구해주세요

df = pd.DataFrame(np.random.randint(1, 100, size=(15, 3)),
			index=[['1학년' for i in range(5)] + ['2학년' for i in range(5)] + ['3학년' for i in range(5)] ,
 [str(i)+'반' for i in range(1,6)] + [str(i)+'반' for i in range(1,6)] + [str(i)+'반' for i in range(1,6)] ],
columns=['국어','영어','과학'])

df

국어  영어  과학
1학년 1반  30  59  77
    2반  30  28  91
    3반  51  21  67
    4반  66  90  25
    5반  87  94  88
2학년 1반  32  86  56
    2반  10  37  58
    3반  70  65  30
    4반  62  93   8
    5반  40  16  46
3학년 1반  25  69  82
    2반  86  84  73
    3반  69  83  65
    4반  70  16  46
    5반  80  32  35

In [ ]:
df.index.names = ['학년','반']
df

국어  영어  과학
학년  반             
1학년 1반  30  59  77
    2반  30  28  91
    3반  51  21  67
    4반  66  90  25
    5반  87  94  88
2학년 1반  32  86  56
    2반  10  37  58
    3반  70  65  30
    4반  62  93   8
    5반  40  16  46
3학년 1반  25  69  82
    2반  86  84  73
    3반  69  83  65
    4반  70  16  46
    5반  80  32  35

In [ ]:
df['합계'] = df['국어'] + df['영어'] + df['과학']
df

국어  영어  과학   합계
학년  반                  
1학년 1반  30  59  77  166
    2반  30  28  91  149
    3반  51  21  67  139
    4반  66  90  25  181
    5반  87  94  88  269
2학년 1반  32  86  56  174
    2반  10  37  58  105
    3반  70  65  30  165
    4반  62  93   8  163
    5반  40  16  46  102
3학년 1반  25  69  82  176
    2반  86  84  73  243
    3반  69  83  65  217
    4반  70  16  46  132
    5반  80  32  35  147

In [ ]:
df['평균'] = df['합계']/3

In [ ]:
df

국어  영어  과학   합계         평균
학년  반                             
1학년 1반  30  59  77  166  55.333333
    2반  30  28  91  149  49.666667
    3반  51  21  67  139  46.333333
    4반  66  90  25  181  60.333333
    5반  87  94  88  269  89.666667
2학년 1반  32  86  56  174  58.000000
    2반  10  37  58  105  35.000000
    3반  70  65  30  165  55.000000
    4반  62  93   8  163  54.333333
    5반  40  16  46  102  34.000000
3학년 1반  25  69  82  176  58.666667
    2반  86  84  73  243  81.000000
    3반  69  83  65  217  72.333333
    4반  70  16  46  132  44.000000
    5반  80  32  35  147  49.000000

In [ ]:
df.groupby('학년').sum()

국어   영어   과학   합계          평균
학년                                 
1학년  264  292  348  904  301.333333
2학년  214  297  198  709  236.333333
3학년  330  284  301  915  305.000000

In [ ]:
#결측지 처리를 해주세요. (age - 평균값적용, Cabin - N 으로, Embarked - N)
#성별(Sex) 생존자 합을 구해주세요
#클래스(Pclass) 별 생존자 합을 구해주세요
#나이(Age) 를 활용 유아, 10대, 20대, 30대, 40대, 50대, 60대, 노인의 생존자 합을 구해주세요.

In [ ]:
df = pd.read_csv("titanic_train.csv")
df.isnull().sum()

PassengerId      0
Survived         0
Pclass           0
Name             0
Sex              0
Age            177
SibSp            0
Parch            0
Ticket           0
Fare             0
Cabin          687
Embarked         2
dtype: int64

In [ ]:
#결측지 처리를 해주세요. (age - 평균값적용, Cabin - N 으로, Embarked - N)
df['Age'].fillna(df['Age'].mean(), inplace = True)
df['Cabin'].fillna('N', inplace = True)
df['Embarked'].fillna('N', inplace = True)

df.isnull().sum()

PassengerId    0
Survived       0
Pclass         0
Name           0
Sex            0
Age            0
SibSp          0
Parch          0
Ticket         0
Fare           0
Cabin          0
Embarked       0
dtype: int64

In [ ]:
#성별(Sex) 생존자 합을 구해주세요
df.groupby('Sex')['Survived'].sum()

Sex
female    233
male      109
Name: Survived, dtype: int64

In [ ]:
#클래스(Pclass) 별 생존자 합을 구해주세요
df.groupby('Pclass')['Survived'].sum()

Pclass
1    136
2     87
3    119
Name: Survived, dtype: int64

In [ ]:
age = 9

def Age_Range(age) :
  if age // 10 == 0 :
    return "유아"
  elif age // 10 == 1 :
    return "10대"
  elif age // 10 == 2 :
    return "20대"
  elif age // 10 == 3 :
    return "30대"
  elif age // 10 == 4 :
    return "40대"
  elif age // 10 == 5 :
    return "50대"
  elif age // 10 == 6 :
    return "60대"
  else :
    return "노인"

In [ ]:
df['연령대'] = df['Age'].apply(Age_Range)

In [ ]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  연령대  
0      0         A/5 21171   7.2500     N        S  20대  
1      0          PC 17599  71.2833   C85        C  30대  
2      0  STON/O2. 3101282   7.9250     N        S  20대  
3      0            113803  53.1000  C123        S  30대  
4      0            373450   8.0500     N        S  30대

In [ ]:
df.groupby('연령대')['Survived'].sum()

연령대
10대     41
20대    129
30대     73
40대     34
50대     20
60대      6
노인       1
유아      38
Name: Survived, dtype: int64

In [ ]:
df[(df['연령대'] == '30대') & (df['Pclass'] == 1)]

PassengerId  Survived  Pclass  \
1              2         1       1   
3              4         1       1   
61            62         1       1   
137          138         0       1   
215          216         1       1   
218          219         1       1   
224          225         1       1   
230          231         1       1   
248          249         1       1   
257          258         1       1   
258          259         1       1   
269          270         1       1   
273          274         0       1   
309          310         1       1   
318          319         1       1   
325          326         1       1   
332          333         0       1   
383          384         1       1   
390          391         1       1   
412          413         1       1   
447          448         1       1   
452          453         0       1   
486          487         1       1   
512          513         1       1   
520          521         1       1   
537          538         1       1   
540          541         1       1   
558          559         1       1   
572          573         1       1   
577          578         1       1   
581          582         1       1   
583          584         0       1   
604          605         1       1   
632          633         1       1   
671          672         0       1   
679          680         1       1   
690          691         1       1   
701          702         1       1   
716          717         1       1   
737          738         1       1   
741          742         0       1   
759          760         1       1   
763          764         1       1   
806          807         0       1   
809          810         1       1   
822          823         0       1   
835          836         1       1   
842          843         1       1   
867          868         0       1   
872          873         0       1   

                                                  Name     Sex   Age  SibSp  \
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
61                                 Icard, Miss. Amelie  female  38.0      0   
137                        Futrelle, Mr. Jacques Heath    male  37.0      1   
215                            Newell, Miss. Madeleine  female  31.0      1   
218                              Bazzani, Miss. Albina  female  32.0      0   
224                       Hoyt, Mr. Frederick Maxfield    male  38.0      1   
230       Harris, Mrs. Henry Birkhardt (Irene Wallach)  female  35.0      1   
248                      Beckwith, Mr. Richard Leonard    male  37.0      1   
257                               Cherry, Miss. Gladys  female  30.0      0   
258                                   Ward, Miss. Anna  female  35.0      0   
269                             Bissette, Miss. Amelia  female  35.0      0   
273                              Natsch, Mr. Charles H    male  37.0      0   
309                     Francatelli, Miss. Laura Mabel  female  30.0      0   
318                           Wick, Miss. Mary Natalie  female  31.0      0   
325                           Young, Miss. Marie Grice  female  36.0      0   
332                          Graham, Mr. George Edward    male  38.0      0   
383  Holverson, Mrs. Alexander Oskar (Mary Aline To...  female  35.0      1   
390                         Carter, Mr. William Ernest    male  36.0      1   
412                             Minahan, Miss. Daisy E  female  33.0      1   
447                        Seward, Mr. Frederic Kimber    male  34.0      0   
452                    Foreman, Mr. Benjamin Laventall    male  30.0      0   
486    Hoyt, Mrs. Frederick Maxfield (Jane Anne Forby)  female  35.0      1   
512                          McGough, Mr. James Robert    male  36.0      0   
520                              Perreault, Miss. Anne  female  30.0      0   
537         

In [ ]:
df[(df['연령대'] == '30대') & (df['Pclass'] == 1)]['PassengerId'].count()

50

In [ ]:
df.groupby('Pclass')['Age'].mean()

Pclass
1    37.048118
2    29.866958
3    26.403259
Name: Age, dtype: float64

In [ ]:
df.groupby(['Pclass','Sex'])['Survived'].count()

Pclass  Sex   
1       female     94
        male      122
2       female     76
        male      108
3       female    144
        male      347
Name: Survived, dtype: int64

In [ ]:
df.groupby(['Pclass','Sex'])['Survived'].sum()

Pclass  Sex   
1       female    91
        male      45
2       female    70
        male      17
3       female    72
        male      47
Name: Survived, dtype: int64

In [ ]:
A = df.groupby(['Pclass','Sex'])['Survived'].sum()
B = df.groupby(['Pclass','Sex'])['Age'].count()

A/B

Pclass  Sex   
1       female    0.968085
        male      0.368852
2       female    0.921053
        male      0.157407
3       female    0.500000
        male      0.135447
dtype: float64

In [ ]:
A = df.groupby(['연령대'])['Survived'].sum()
B = df.groupby(['연령대'])['Survived'].count()

A/B

연령대
10대    0.401961
20대    0.324937
30대    0.437126
40대    0.382022
50대    0.416667
60대    0.315789
노인     0.142857
유아     0.612903
Name: Survived, dtype: float64